export const ENDPOINTS = {
    OAUTH: 'v3/oauth/token/generate',
    PING: 'ping',
    BRAND_REWARDS: 'api_gateway/rewards/core/v1/reward/brand',
    HEALTH_SCORE: 'health-profile/health-score',
    MISSION: 'missions',
    MISSION_DETAILS: 'missions/details',
    MISSION_CATEGORIES: 'activity-category',
    MISSION_PROGRESS: 'missions/progress',
    MISSION_TRACKING_HISTORY: 'missions/tracking-history',
    MISSION_UPDATE_MISSION_PROGRESS: 'missions/progress',
    MISSION_ENROLL: 'missions/enroll',
    MISSION_UNENROLL: 'missions/unenroll',
    REWARDABLE_ACTIVITES: 'rewardable-activities',
    REWARDABLE_GET_DETAIL: 'rewardable-activities/detail',
    HEALTH_SURVEY: 'rewardable-activities/health-survey/save',
    HEALTH_SURVEY_GET: 'rewardable-activities/detail',
    QUIZ: 'rewardable-activities/quiz/submit',
    GYM_CHECKIN_PROGREESS: 'rewardable-activities/gym-checkin/progress',
    GYM_CHECKIN_OVERALL_PROGRESS:
        'rewardable-activities/gym-checkin/overall-progress',
    MYACTIVITES: 'user/my-activities',
    REWARDABLE_CLAIM_REWARDS: 'rewardable-activities/claim-reward',
    RALLY_STRIDE_HISTORY:
        'rewardable-activities/rally-stride/tracking-history?',
    USER_SCREEN_NAME: 'user/screen-name',
    USER_LEGAL_AUTH: 'user/legal-auths',
    CHALLENGES_DETAIL: 'challenges/details',
    CHALLENGE_DETAIL_BYCODE: 'challenges/detail-by-code',
    CHALLENGE_PROGRESS: 'challenges/progress',
    CHALLENGES_ENROLL: 'challenges/enroll',
    challenges_unenroll: 'challenges/unenroll',
    HEALTH_FACTOR: 'health-profile/health-factors',
    HEALTH_BIOMETRIC_KPI: 'health-profile/biometric-kpi/details',
    REWARDS_GIFTCARDS: 'rewards/gift-cards/my-gift-cards',
    REDEEM_DONATION: 'rewards/donations/redeem',
}
